name: "CI pipeline"

on:
  push:
    branches:
      [main]
  pull_request:
    branches:
      [main]

jobs:
  test:
    runs-on: ubuntu-latest #windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: node instalacja
        uses: actions/setup-node@v6
        with:
          node-version: 24
          #cache: npm

      - name: cache
        uses: actions/cache@v5
        with:
          path: ~/.npm #na windows to byłby ~/Appdata/Local/npm-cache , 'npm config get cache' pokazuje lokalizacje cache na danym urządzeniu :)
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }} #tu klucz może być inny ale czytałam, że najczęściej używa się hashu pliku lock z zależnościami

      - run: npm install
      
      - run: npx eslint .

      - run: npm test

